---

name: Semantic versioning parser
description: GitHub action for parsing semantic versions
branding:
  icon: bookmark
  color: green
inputs:
  tag:
    description: The full semantic version to parse (e.g., v1.2.3 or 1.2.3)
    required: true
outputs:
  has_prefix:
    description: Whether the version has a prefix (true/false)
    value: ${{ steps.parse.outputs.has_prefix }}
  major:
    description: The major version number
    value: ${{ steps.parse.outputs.major }}
  minor:
    description: The minor version number
    value: ${{ steps.parse.outputs.minor }}
  patch:
    description: The patch version number
    value: ${{ steps.parse.outputs.patch }}
runs:
  using: composite
  steps:
    - name: Validate version input
      shell: bash
      run: |
        if [[ ! ${{ inputs.tag }} =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Expected format: vX.Y.Z or X.Y.Z"
          exit 1
        fi
    - name: Parse version input
      id: parse
      shell: bash
      run: |
        version="${{ inputs.tag }}"
        has_prefix="false"
        if [[ "$version" == v* ]]; then
          has_prefix="true"
          version="${version#v}"
        fi
        IFS='.' read -r major minor patch <<< "$version"
        echo "has_prefix=$has_prefix" >> $GITHUB_OUTPUT
        echo "major=$major" >> $GITHUB_OUTPUT
        echo "minor=$minor" >> $GITHUB_OUTPUT
        echo "patch=$patch" >> $GITHUB_OUTPUT
