---

name: Semantic versioning parser
description: GitHub action for parsing semantic versions
branding:
  icon: bookmark
  color: green
inputs:
  tag:
    description: The full semantic version to parse
    required: true
outputs:
  patch:
    description: The patch version number
    value: ${{ steps.parse.outputs.patch }}
  minor:
    description: The minor version number
    value: ${{ steps.parse.outputs.minor }}
  major:
    description: The major version number
    value: ${{ steps.parse.outputs.major }}
runs:
  using: composite
  steps:
    - name: Validate version input
      run: |
        if [[ ! ${{ inputs.tag }} =~ (^refs/tags/)?v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Expected format: refs/tags/vX.Y.Z, refs/tags/X.Y.Z, vX.Y.Z or X.Y.Z"
          exit 1
        fi
    - name: Parse version input
      id: parse
      run: |
        version="${{ inputs.tag }}"
        version="${version##*/}"
        version="${version#v}"
        IFS='.' read -r major minor patch <<< "$version"
        echo "major=$major" >> $GITHUB_OUTPUT
        echo "minor=$minor" >> $GITHUB_OUTPUT
        echo "patch=$patch" >> $GITHUB_OUTPUT
