---

name: Semantic versioning parser
description: GitHub action for parsing semantic versions
branding:
  icon: bookmark
  color: green
inputs:
  version:
    description: The full semantic version to parse
    required: true
outputs:
  patch:
    description: The patch version tag
    value: ${{ steps.patch.outputs.version }}
  minor:
    description: The minor version tag
    value: ${{ steps.minor.outputs.version }}
  major:
    description: The major version tag
    value: ${{ steps.major.outputs.version }}
runs:
  using: composite
  steps:
    - name: Get patch version
      id: patch
      run: echo "version=$(echo ${{ inputs.version }} | cut -d / -f 3)" >> $GITHUB_OUTPUT
    - name: Get minor version
      id: minor
      run: echo "version=$(echo ${{ steps.patch.outputs.version }} | cut -d '.' -f 1,2)" >> $GITHUB_OUTPUT
    - name: Get major version
      id: major
      run: echo "version=$(echo ${{ steps.patch.outputs.version }} | cut -d '.' -f 1)" >> $GITHUB_OUTPUT
